### ISSUE TITLE
Hardfault when accessing self.flags

### ISSUE THREAD

**Issue by haata** [mvirkkunen/rtt-target#18]
I'm trying to debug a hardfault issue that seems to be coming from rtt-target.

```
(gdb) l
77	    pub fn is_initialized(&self) -> bool {
78	        self.buffer != ptr::null_mut()
79	    }
80	
81	    pub(crate) fn mode(&self) -> ChannelMode {
82	        let mode = self.flags.load(SeqCst) & 3;
83	
84	        if mode <= 2 {
85	            unsafe { core::mem::transmute(mode) }
86	        } else {
(gdb) p mode
$1 = {fn (*mut rtt_target::rtt::RttChannel) -> rtt_target::ChannelMode} 0x4255fa <rtt_target::rtt::RttChannel::mode>
(gdb) s

Program received signal SIGTRAP, Trace/breakpoint trap.
gemini::__cortex_m_rt_HardFault_trampoline (
    frame=<error reading variable: Cannot access memory at address 0x1fffffe4>) at src/bin.rs:310
310	#[exception]
(gdb)
```

```
(gdb) bt
#0  rtt_target::rtt::RttChannel::mode (self=0x2001f9f8 <_SEGGER_RTT+24>)
    at /home/hyatt/.cargo/registry/src/github.com-1ecc6299db9ec823/rtt-target-0.3.1/src/rtt.rs:82
#1  0x00425776 in rtt_target::rtt::RttWriter::write (self=0x2000016c, buf=...)
    at /home/hyatt/.cargo/registry/src/github.com-1ecc6299db9ec823/rtt-target-0.3.1/src/rtt.rs:191
#2  0x00426314 in rtt_target::{{impl}}::write_str (self=0x2000016c, s=...)
    at /home/hyatt/.cargo/registry/src/github.com-1ecc6299db9ec823/rtt-target-0.3.1/src/lib.rs:335
#3  0x0042616a in core::fmt::{{impl}}::write_str<rtt_target::TerminalWriter> (self=0x200000ec, s=...)
    at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927/library/core/src/fmt/mod.rs:191
#4  0x00428d14 in core::fmt::write () at library/core/src/fmt/mod.rs:1093
#5  0x004260f6 in core::fmt::Write::write_fmt<rtt_target::TerminalWriter> (self=0x2000016c, args=...)
    at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927/library/core/src/fmt/mod.rs:184
#6  0x00426796 in rtt_target::print::print_impl::write_fmt::{{closure}} (w=...)
    at /home/hyatt/.cargo/registry/src/github.com-1ecc6299db9ec823/rtt-target-0.3.1/src/print.rs:116
#7  0x00426750 in rtt_target::print::print_impl::with_writer::{{closure}}<closure-0> (
    args_ptr=0x20000274)
    at /home/hyatt/.cargo/registry/src/github.com-1ecc6299db9ec823/rtt-target-0.3.1/src/print.rs:98
#8  0x00425ed6 in core::ops::function::FnOnce::call_once<closure-0,(*mut ())> ()
    at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927/library/core/src/ops/function.rs:227
#9  0x00425e82 in rtt_target::print::set_print_channel::{{closure}}::{{closure}} ()
    at /home/hyatt/.cargo/registry/src/github.com-1ecc6299db9ec823/rtt-target-0.3.1/src/print.rs:75
#10 0x00425d9e in cortex_m::interrupt::free<closure-0,()> (f=...)
    at /home/hyatt/.cargo/registry/src/github.com-1ecc6299db9ec823/cortex-m-0.7.2/src/interrupt.rs:64
#11 0x00425ea4 in rtt_target::print::set_print_channel::{{closure}} (arg=0x20000274,
    f=0x425ec7 <core::ops::function::FnOnce::call_once<closure-0,(*mut ())>>)
    at /home/hyatt/.cargo/registry/src/github.com-1ecc6299db9ec823/rtt-target-0.3.1/src/print.rs:75
#12 0x00425ebe in core::ops::function::FnOnce::call_once<closure-0,(*mut (), fn(*mut ()))> ()
    at /rustc/3e99439f4dacc8ba0d2ca48d221694362d587927/library/core/src/ops/function.rs:227
#13 0x004266ee in rtt_target::print::print_impl::with_writer<closure-0> (number=0, f=...)
    at /home/hyatt/.cargo/registry/src/github.com-1ecc6299db9ec823/rtt-target-0.3.1/src/print.rs:94
#14 0x0042676c in rtt_target::print::print_impl::write_fmt (number=0, arg=...)
    at /home/hyatt/.cargo/registry/src/github.com-1ecc6299db9ec823/rtt-target-0.3.1/src/print.rs:115
#15 0x00424f5e in kiibohd_log::{{impl}}::log (self=0x42b0e4 <gemini::LOGGER>, record=0x20000414)
    at /home/hyatt/Source/kiibohd/kiibohd-core/kiibohd-log/src/lib.rs:72
#16 0x004278b6 in log::__private_api_log (args=..., level=log::Level::Trace)
    at /home/hyatt/.cargo/registry/src/github.com-1ecc6299db9ec823/log-0.4.14/src/lib.rs:1460
#17 0x0041914c in atsam4_hal::udp::endpoint::Endpoint::alloc (
    self=0x2001f930 <gemini::initLocals::new::USB_BUS+16>,
    ep_type=usb_device::endpoint::EndpointType::Interrupt, ep_dir=usb_device::UsbDirection::In,
    max_packet_size=64, interval=0) at /home/hyatt/git/atsam-rs/atsam4-hal/src/udp/endpoint.rs:85
#18 0x0041ed02 in atsam4_hal::udp::bus::{{impl}}::alloc_ep::{{closure}} (cs=0x20000774)
    at /home/hyatt/git/atsam-rs/atsam4-hal/src/udp/bus.rs:88
#19 0x00418bc0 in cortex_m::interrupt::free<closure-1,core::result::Result<usb_device::endpoint::EndpointAddress, usb_device::UsbError>> (f=...)
    at /home/hyatt/.cargo/registry/src/github.com-1ecc6299db9ec823/cortex-m-0.7.2/src/interrupt.rs:64
#20 0x004152a2 in atsam4_hal::udp::bus::{{impl}}::alloc_ep (
    self=0x2001f928 <gemini::initLocals::new::USB_BUS+8>, ep_dir=usb_device::UsbDirection::In,
    ep_addr=..., ep_type=usb_device::endpoint::EndpointType::Interrupt, max_packet_size=64, interval=0)
    at /home/hyatt/git/atsam-rs/atsam4-hal/src/udp/bus.rs:87
#21 0x0040845e in usb_device::bus::UsbBusAllocator<atsam4_hal::udp::bus::UdpBus>::alloc<atsam4_hal::udp::bus::UdpBus,usb_device::endpoint::In> (self=0x2001f924 <gemini::initLocals::new::USB_BUS+4>, ep_addr=...,
    ep_type=usb_device::endpoint::EndpointType::Interrupt, max_packet_size=64, interval=0)
    at /home/hyatt/.cargo/git/checkouts/usb-device-9279830215736247/76470f9/src/bus.rs:236
#22 0x00408672 in usb_device::bus::UsbBusAllocator<atsam4_hal::udp::bus::UdpBus>::interrupt<atsam4_hal::udp::bus::UdpBus,usb_device::endpoint::In> (self=0x2001f924 <gemini::initLocals::new::USB_BUS+4>,
    max_packet_size=64, interval=0)
    at /home/hyatt/.cargo/git/checkouts/usb-device-9279830215736247/76470f9/src/bus.rs:292
--Type <RET> for more, q to quit, c to continue without paging--c
#23 0x00409f8e in usbd_hid::hid_class::HIDClass<atsam4_hal::udp::bus::UdpBus>::new_ep_in<atsam4_hal::udp::bus::UdpBus> (alloc=0x2001f924 <gemini::initLocals::new::USB_BUS+4>, report_descriptor=..., poll_ms=0, settings=...) at /home/hyatt/git/usbd-hid/src/hid_class.rs:238
#24 0x0040d406 in kiibohd_usb::HidInterface<atsam4_hal::udp::bus::UdpBus>::new<atsam4_hal::udp::bus::UdpBus> (alloc=0x2001f924 <gemini::initLocals::new::USB_BUS+4>, locale=usbd_hid::hid_class::HidCountryCode::NotSupported) at /home/hyatt/Source/kiibohd/kiibohd-core/kiibohd-usb/src/lib.rs:29
#25 0x0040bea0 in gemini::init (cx=...) at src/bin.rs:148
#26 0x0040d046 in gemini::APP::main () at src/bin.rs:59
```
rprintln! does work for a while, but there seems to be a condition that causes rtt to self-destruct. My suspicion is formatted strings with a bunch of args.

I'm not super familiar with RTT and where the buffers are stored (maybe there's some stack corruption going on?).

**Comment by haata** [comment]
The chip I'm debugging is an atsam4s8b (thumbv7em-none-eabi) using https://github.com/atsam-rs/atsam4-hal

**Comment by haata** [comment]
So I think I may have figured out what's going on (not sure if this is intended though).
```rust
rprintln!("This works!");
cortex_m::interrupt::free(|cs| {
    rprintln!("This does not work");
}
```

**Comment by haata** [comment]
Turns out my issue was gdb and jlink not setting the stack pointer correctly causing seemingly deterministic hardfaults due to prematurely running out of stack. Sorry for the noise.
